### ISSUE TITLE
Terraform resources for Config and CloudTrail in GovCloud

### ISSUE THREAD

**Issue by JacobWeyer** [lacework/terraform-provider-lacework#103]
Allows Access Key/Secret Key
https://github.com/lacework/terraform-provider-lacework/blob/main/lacework/resource_lacework_integration_ecr.go#L94

Doesn't allow it in Cloudtrail or Config
https://github.com/lacework/terraform-provider-lacework/blob/main/lacework/resource_lacework_integration_aws_ct.go#L55
https://github.com/lacework/terraform-provider-lacework/blob/main/lacework/resource_lacework_integration_aws_cfg.go#L58

Is there a reason for this? It'd make our GovCloud integration so much easier to implement if we were able to pass our access keys in through our terraform to create the Lacework integrations as our organization has 18 AWS accounts in both places. Obviously for non govcloud we can use the role and external ID. However for every account/region we run config in we will need to add keys multiple times and it seems like a needless hassle.

**Comment by afiune** [comment]
Hi @JacobWeyer 👋🏽 and thank you so much for your feedback! 

I think you are trying to configure AWS Config and Cloudtrail integrations for GovCloud, which are not yet supported, we are, at the moment, doing some work to migrate our tools and integrations (including our Terraform provider) to our latest API v2, after that we will be implementing these features.

I will talk about this feature with my team and try to prioritize it, a quick question for you, would you be willing to help us with testing during development? or you rather just wait until we tackle it and you can use it from the official releases in the Terraform Registry?

**Comment by afiune** [comment]
**JIRA: ALLY-480**

**Comment by JacobWeyer** [comment]
To be clear, you mean the terraform resources for Config and CloudTrail aren't supported right?

Most likely we will have to go ahead and create these integrations by hand but I'd definitely be interested in assisting with any testing as needed. My hope is that the API already allows for that feature as the keys and govcloud are supported via the UI and that the Lacework SDK & Provider just need updates to allow these options.

Please let us know! 

jweyer@xometry.com

**Comment by afiune** [comment]
@JacobWeyer It is exactly what you said. Everything is lined up, we just have to work on the SDK and Provider, we will do our best to get to work on these features in the next sprint. As soon as we start working on them we will notify you so that you can help us with testing. 💯 🥇 🙌🏽

**Comment by xometry-johnny** [comment]
Hi, is there an update on this?

**Comment by afiune** [comment]
Hi @xometry-johnny - Yes! We have an update 🙌🏽 🎉 

We are working on these features as we speak, there are already a couple Pull Requests you can look:
* https://github.com/lacework/terraform-provider-lacework/pull/106
* https://github.com/lacework/go-sdk/pull/421

Once we finish its development we will release them and notify this issue, we expect to have this ready no later than the end of this week.

Would you be also interested in helping us test these features? Let us know so we can reach out.

**Comment by xometry-johnny** [comment]
@afiune this is awesome! yea we be willing to help tests. How can I help?

**Comment by afiune** [comment]
@xometry-johnny @JacobWeyer Great news! 🎉 

![tenor-204655390](https://user-images.githubusercontent.com/5712253/119872873-2a357e80-bee1-11eb-9576-b912dc9a9f5b.gif)

We have completed the development of these two new features, we are about to release them with https://github.com/lacework/terraform-provider-lacework/pull/111

You can find documentation on how to integrate with both, Config and CloudTrail for AWS GovCloud at the Terraform Registry:
* https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/integration_aws_govcloud_cfg
* https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/integration_aws_govcloud_ct

Thank you so much for the feedback! Do not hesitate to reach out to us with any doubt, question, or issue you may have.
