### ISSUE TITLE
bug: How is the lacework module able to introduce breaking changes when I am using a lock file?

### ISSUE THREAD

**Issue by red8888** [lacework/terraform-provider-lacework#231]
I just started see these errors today:
```
Error: Unsupported argument

  on .terraform/modules/aws_cloudtrail/main.tf line 299, in resource "aws_iam_policy" "cross_account_policy":
 299:   tags        = var.tags

An argument named "tags" is not expected here.
```

The Lacework module seems to keep introduces changes to its configuration. But I never upgrade any of my providers and I'm using a lockfile so how is this possible?

Maybe I'm doing something wrong, but I want to check if you guys are like overwriting previously published versions of the module or something? How could this be possible? This doesn't happen with any of my other tf providers.

**Comment by afiune** [comment]
Hello @red8888 - We are sorry to hear you are experiencing some issues with our Terraform modules,
let me see if we can get to the bottom of this issue.

Terraform modules work differently from Terraform providers, even if you are using a `.lock` file, they
don't get pinned there. Try to look the file up and you won't see any reference to any module, at least not
that I know of.

Our modules follow the https://semver.org/ version convention, which means that we never introduce breaking
changes to PATCH and MINOR version bumps, we would only do a MAJOR version bump if there are breaking
changes. Having said that, I would like to know which version of the AWS CloudTrail Module are you using so
I can see if we made a mistake with a breaking change. 

To pin Modules to specific versions and not let them upgrade, you should move away from the pessimistic
operator `~> 0.1` and move to a hard-pinning like `= 0.1.32` - This is the way modules are restricted from upgrading.

We apologies for the inconveniences and look forward to hearing from you so we can troubleshoot this problem further.

**Comment by red8888** [comment]
This explains the issue then. I assumed that the lock file included modules, but it does not. This makes sense because this is the only community module we use that depends on other providers than its own.

I'll just pin the module version.
