### ISSUE TITLE
feat: Container registries limit by number

### ISSUE THREAD

**Issue by jrobison-sb** [lacework/terraform-provider-lacework#270]
# Feature Request

**Describe the Feature Request**

The Lacework API call for ContainerRegistries requires that limitNumImg be one of 5, 10, 15. The Terraform provider should validate that one of those values is used.

**Describe Preferred Solution**
Validate that limitNumImg is one of 5, 10, 15.

**Additional Context**
https://github.com/lacework/terraform-provider-lacework/blob/main/lacework/resource_lacework_integration_ecr.go#L179

https://yourlacework.lacework.net/api/v2/docs#tag/ContainerRegistries/paths/~1api~1v2~1ContainerRegistries/post

https://github.com/lacework/terraform-aws-ecr/pull/25#discussion_r811164084

**Comment by dmurray-lacework** [comment]
Thanks for raising this @jrobison-sb I've created a ticket for this on our board ->
https://lacework.atlassian.net/browse/ALLY-889

**Comment by dmurray-lacework** [comment]
This change is in review -> https://github.com/lacework/terraform-provider-lacework/pull/283 and will be released in v0.17.0 of the terraform-provider-lacework
