### ISSUE TITLE
feat: Is there anything limiting this to use in the China AWS regions?

### ISSUE THREAD

**Issue by JacobWeyer** [lacework/terraform-provider-lacework#273]
# Feature Request

**Describe the Feature Request**
We'd like to use Lacework's AWS integrations in China

**Is your feature request related to a problem? Please describe**
We're unaware of whether Lacework is supported in AWS China. It's similar to GovCloud though.

**Describe Preferred Solution**
Really just looking for guidance or any knowledge of other users doing the same thing.

**Additional Context**
Seems like GovCloud might work as long as the resources check the partition of the requesting AWS resource rather than assuming they'll be `aws-us-gov`.

**Comment by Karmali** [comment]
Lacework is not currently supported in AWS China. However, we are exploring adding this to our roadmap. Your comment re: GovCloud is also right, but there are several product and regulatory prerequisites that we need to flesh out. Happy to talk more if you like.

**Comment by dmurray-lacework** [comment]
Closing this until there is a request from product.
