### ISSUE TITLE
bug: Was module version 0.12.2 modified?

### ISSUE THREAD

**Issue by red8888** [lacework/terraform-provider-lacework#299]
I have this in my tf config:
```
  required_providers {
    lacework = {
      source  = "lacework/lacework"
      version = "0.12.2"
    }
 ...
```

This was working without issues, but recently when I tried to initialize I saw this error:
```
Error: Failed to query available provider packages

Could not retrieve the list of available versions for provider hashicorp/aws:
locked provider registry.terraform.io/hashicorp/aws 3.66.0 does not match
configured version constraint >= 3.0.0, >= 3.35.0, ~> 4.0, < 5.0.0; must use
terraform init -upgrade to allow selection of new versions
```

I seems like the version constraint of aws of the lacework provider changed somehow.

Maybe I'm misunderstanding something but Im trying to figure out how this could happen.

I have the module pinned to 0.12.2 so the version constraints should never change right? Was module version "0.12.2" overwritten or something?

**Comment by dmurray-lacework** [comment]
Hi @red8888 The Lacework provider does not depend on any other provider. You must being using one of our modules, can you tell use what module and version is being used. 

You can use the command `terraform providers` to get the list of providers and modules

**Comment by red8888** [comment]
I didn't realize I was using the modules too. It was the recently released versions of the aws config and cloudwatch modules. I pinned the previous versions and that solved my issue
