### ISSUE TITLE
bug: Email Alert Channel Deployments are Not Manageable if Their GUIDs Change

### ISSUE THREAD

**Issue by coashby-lw** [lacework/terraform-provider-lacework#300]
# Description
Lacework email alert channels that are part of a terraform state, are not manageable if their GUIDs have been modified or deleted due to user (console or programmatic) interactions.

# Steps to Reproduce the Behavior
1. Create an email alert channel using the Lacework Terraform provider
    ```code
    terraform {
        required_providers {
            lacework = {
                source  = "lacework/lacework"
                version = "0.17.0"
            }
        }
    }
    provider "lacework" {
        # Configuration options
    }

    resource "lacework_alert_channel_email" "my_email_notification" {
        name     = "My Email Notification"
        recipients = [
            "corey.ashby@lacework.net"
        ]
    }
    ```
2. Run the following command to apply the change to your Lacework account.
    ```sh
    > terraform apply -auto-approve
    ```

3. Using the default Lacework account specified by the configured terraform host environment, navigate to **<Settings | Alert Channels>** and delete the event.

4. Check the current state of your infrastructure to validate that it has (or hasn't) changed.
    ```sh
    terrafrom plan
    ```

# Expected Behavior
It is expected that the Terraform script described in the [Steps to Reproduce the Behavior](#steps-to-reproduce-the-behavior) can be used to:
1. Describe the change that exists between the current infrastructure state and the desired state defined in the script. Specifically,
    - no email alert channel matching name: "My Email Notification" and
    - recipients list: ["corey.ashby@lacework.com"]

    exists.

2. Apply the desired state so that one alert channel (regardless of GUID) matches the desired configuration.

# Current Behavior
Step 4 in [Steps to Reproduce the Behavior](#steps-to-reproduce-the-behavior) results in the following message:
```sh
> terraform plan               
lacework_alert_channel_email.my_email_notification: Refreshing state... [id={IntGUID}]
╷
│ Error: 
│   [GET] https://{account}.lacework.net/api/v2/AlertChannels/{IntGUID}
│   [404] Not found
│ 
│   with lacework_alert_channel_email.my_email_notification,
│   on main.tf line 13, in resource "lacework_alert_channel_email" "my_email_notification":
│   13: resource "lacework_alert_channel_email" "my_email_notification" {
│ 
╵
```

# Test System
 - OS: macOS Monterey 12.2 (Apple M1 Pro)
 - Provider Version: 0.17.0

# Additional Context
The resource `lacework_alert_channel_email` is defined for creating email alert channels or modifying existing email alert channels imported using the corresponding GUID. The same GUID is also used as part of the API endpoint when retrieving information regarding the resource. This, however, places a dependency on the GUID itself being the monitored state, rather than the configuration arguments: `name`, `recipients`, `enabled` status, and how many resources with the given configuration arguments have been requested (Lacework does not restrict duplicate names).

The GUID value is now behaviorally introduced as part of the state. If the GUID that is present in the terraform state, differs from what is currently deployed, then this criteria prevents any other stateful criteria from being evaluated, effectively short-circuiting any of the advertised stateful conditions.

The failure to find a matching GUID, as evident by a HTTP 404 status code, does correlate with a change in the infrastructure, however, it does not represent sufficient criteria for establishing its existence in the infrastructure, or that a value in: `name`, `recipients`, or `enabled` changed. Therefore, it should not be treated as an unhandled condition. This detected change should trigger a deeper inspection. The state that the end user is concerned with should be based solely on configuration arguments advertised and the number of resources matching that description.  

Seems related to the issue below:
bug: if lacework_alert_channel_slack fails, provider has resource in state, but it does not exist in Lacework: #181

**Comment by coashby-lw** [comment]
I have recently been instructed to consider the rules regarding the _ownership_ scope of Terraform resources. Terraform will only manage resources that it creates, and nothing else. This being the case, if a resource mapping to an alert channel GUID, as in the above example, has been removed, then what is known is that a single managed resource is missing and should be replaced. The stateful nature of terraform will NOT extend beyond the resource to examine and manage the state of ALL alert channel integrations. The proposed behavior in the Additional Context section suggests this behavior and that extends beyond the scope of the Terraform provider resource.

The stateful criteria we wish to maintain is that if Terraform is managing a specific number of resources, N, and  N resource can not be found, then it is expected that the difference is detected and new resources are created/destroyed to maintain the desired state.

**Comment by afiune** [comment]
Jira: https://lacework.atlassian.net/browse/ALLY-981

**Comment by afiune** [comment]
Closed by https://github.com/lacework/terraform-provider-lacework/pull/308
