### ISSUE TITLE
feat: Support for creating policy exceptions

### ISSUE THREAD

**Issue by getsec** [lacework/terraform-provider-lacework#322]
# Feature Request
> Please let me know if this already exists, or if i'm missing something.

**Describe the Feature Request**
As a lacework customer and a security/IAC user, I want the ability to setup custom lacework policies for our alerts. 

**Is your feature request related to a problem? Please describe**
No

**Describe Preferred Solution**
As an example  take a look at the uploaded photo. We have a list of users we want to exclude from some of these policies as our service is expected for `squid` to reach out to a bunch of bad places. Since we have multiple tenants, updating this value in the console in multiple places is both cumbersome, and prone to error.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/13003926/172909951-4ed09683-f0f9-44eb-9594-f861715b2902.png">

I see that https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/policy is a resource that can be used. Can we use this for HOST/APPLICATION policies and not just cloudtrail / LQL queries?

thanks

**Comment by afiune** [comment]
@getsec Thank you so much for your feedback! 🎉

We have the ability to manage Lacework policies via Terraform with the resource `lacework_policy`:

- https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/policy

But we do not have the ability yet to add Policy Exceptions.

This is in our roadmap in the "next to work on" features. We will keep you posted as soon as we release this feature. 👍🏽 

-- https://lacework.atlassian.net/browse/ALLY-1036

**Comment by dmurray-lacework** [comment]
Resolved by https://lacework.atlassian.net/browse/GROW-1036
