### ISSUE TITLE
fix: vulnerability exception resources should not always pass Fixable field

### ISSUE THREAD

**Issue by matthewashley1** [lacework/terraform-provider-lacework#339]
# Feature Request

**Describe the Feature Request**
To have the fixable parameter of vulnerability criteria for a vulnerability exception container to not get defined by default.

**Is your feature request related to a problem? Please describe**
I am attempting the setup vulnerability exceptions and would like to set exceptions for multiple CVES. I however do not care if a CVE is fixable or not and would not like to constrain the scope of my exceptions for fixable. When creating vulnerability exceptions with the lacework terraform provider the fixable parameter gets set by default to false causing my inline scanner runs in my jenkins pipeline to fail. I want to define one vulnerability exception for multiple CVES that are a mix of having a fix version or not. Currently, the lacework terraform provider is not allowing me to do that as the fixable parameter is set by default. 

**Describe Preferred Solution**
To have the ability to not set the fixable parameter of vulnerability criteria for a vulnerability exception container.

**Additional Context**
Provider Version: 0.20.1

**Comment by afiune** [comment]
Hi @matthewashley1 - Thank you so much for your feedback!

I looked quickly in the code and it indeed looks we are always passing the Fixable parameter, I have created an
internal ticket for my team to tackle this issue in our next sprint, we will let you know once this is fixed.

- https://lacework.atlassian.net/browse/ALLY-1085

**Comment by afiune** [comment]
Hi @matthewashley1 👋🏽 - We closed this issue before making the modifications in our Terraform provider.

![tenor-63466038](https://user-images.githubusercontent.com/5712253/182282045-811d8ccc-5d27-4a29-8556-76fae14d78fa.gif)

Good news, we just fixed this issue! 🙌🏽

![tenor-143493384](https://user-images.githubusercontent.com/5712253/182282169-64b9c830-9fec-42f4-ac88-37b736119f29.gif)

Unfortunately, Terraform doesn't have (yet) a great solution for this cases where we need to have a tristate
boolean. 

- Read more about this here -> https://github.com/hashicorp/terraform-plugin-sdk/issues/817

The approach we took was to introduce a new argument inside the `vulnerability_criteria` named `fixable_vuln`,
this new argument is of type `string` and it solves the tristate boolean issue.

The (tres) states are:
* `"false"` (Yes! A string with value `false`) - Constraints the exception by **non-fixable** vulnerabilities
* `"true"` (A string with value `true`) - Constraints the exception by **fixable** vulnerabilities
* `""` (empty string) - **Do not filter** by fixable or non-fixable vulnerability


Use the latest version of our provider [`v0.22.2`](https://github.com/lacework/terraform-provider-lacework/releases/tag/v0.22.2) and let us know if this fixes your use case.

Note that we deprecated the previous boolean argument `fixable` and it will be removed on version
`v1.0` of our provider.

Thank you so much for reporting this issue!

**Comment by matthewashley1** [comment]
Hello @afiune, thank you for your quick response and the great work your team has put into this bug. Yes, this implementation has fixed my issue and works great for my use case. This is now live in my team's production terraform deployment. 👍 👏
