### ISSUE TITLE
bug: provider not respecting subaccount argument

### ISSUE THREAD

**Issue by relsqui** [lacework/terraform-provider-lacework#383]
**Describe the bug**
When I follow the [instructions to import a lacework_agent_access_token](https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/agent_access_token#import), Terraform reports a 500 error from the server. This is consistent with the API's response when I call the same endpoint through the CLI, and it's [marked as deprecated in the docs](https://opensesame.lacework.net/api/v1/external/docs).

**To Reproduce**
1. Create a Terraform config with a `lacework_agent_access_token` and appropriate provider auth.
2. Create an agent token (through the CLI or UI) and copy its value
3. `terraform import lacework_agent_access_token.this <token redacted>`
4. See:

```
╷
│ Error:
│   [GET] https://opensesame.lacework.net/api/v1/external/tokens/<token redacted>
│   [500] Internal Server Error
│
│
╵
```

Or, easier, now that we have the endpoint in the error message:
1. Configure auth with the Lacework CLI for an account with an agent token in it
2. `lacework agent token list`
3. Copy a token value
4. `lacework api get /v1/external/tokens/<token redacted>`
5. See (command usage information and):

```
ERROR unable to send the request:
  [GET] https://opensesame.lacework.net/api/v1/external/tokens/<token redacted>
  [500] Internal Server Error
```

**Expected behavior**
Token is imported into Terraform state

**Please complete the following information):**
 - OS: Ubuntu 20.04.5 via WSL in Windows 10
 - Provider Version: 0.26.1

**Additional context**
Would love to hear I'm just using it wrong :) I tried using the name instead of the value, which was the only other thing I could think of.

**Comment by afiune** [comment]
@relsqui Hi there 👋🏽 - We are sorry you are experiencing some difficulties with this resource, importing an Agent Access Token is supported and should be working as expected, though seeing the error message you posted, the only think I can think of is that you are trying to import an agent token from a different Lacework sub-account.

I see that your Lacework account is an organization so please make sure that the Terraform provider for Lacework is configured to the right sub-account. You can change sub-accounts with the argument `subaccount`.

E.g.
```hcl
provider "lacework" {
    subaccount = "your-acccount"
} 
```

If the problem persist let me know, I will take a closer look at your issue.

**Comment by relsqui** [comment]
Oh hi, thanks for the quick response. I didn't paste my provider config because we're actually using Terragrunt (so there's an extra layer of indirection), but I'm quite confident the subaccount is correct because we're already using it to deploy the agentless scanning configuration into a bunch of accounts.

It also wouldn't explain why the API call through the Lacework CLI doesn't work -- when I actually run those commands, I'm including `--subaccount shared-services-dev` both times. It successfully retrieves the token (and I can list tokens with `api get /v1/external/tokens`), but when I add the token to the endpoint it 500s.

Am I maybe misunderstanding how I'm supposed to pass the token into the endpoint (or import command)? The docs say "the token itself," which I took to mean the token value.

**Comment by relsqui** [comment]
We might both be right! Here's the generated provider configuration:

```
  provider "lacework" {
    account     = "opensesame.lacework.net"
    subaccount  = "shared-services-dev"
    api_key     = "[redacted]"
    api_secret  = "[redacted]"
  }
```

... but when I used equivalent config across many subaccounts to generate an agent token in each, all the tokens were created in the top-level "opensesame" account, not the named subaccounts.

This would certainly explain why I wasn't able to import the token from the intended account, if this config was operating on the top-level account instead, but I'm still confused about why that is, given the above provider. I remember hearing from support in March that there was a bug in the provider about using subaccounts, but also that it was fixed back in 0.17.0. So hopefully I'm still missing something?

(I do notice, as I review the docs, that I'm supposed to just have "opensesame" as the account in the provider instead of the full domain, but when I `terraform state show` one of the tokens, it shows the account as "opensesame"  -- I'll fix the config, but the provider seems to be understanding what I meant anyway. Also, just to be thorough: "we're already using it to deploy the agentless scanning configuration into a bunch of accounts" turned out to be a red herring. It's true, but `terraform state list` tells me the module is only deploying resources into AWS anyway, and only reading from the Lacework provider.)

**Comment by relsqui** [comment]
Okay, confirmed with a simple repro that specifying a subaccount isn't working as I expect it to. Here's my `~/.lacework.toml`:

```toml
[default]
  account = "opensesame"
  api_key = "<redacted>"
  api_secret = "<redacted>"
  version = 2
```

And here's a standalone Terraform file:

```hcl
terraform {
  required_version = "~> 1.0"

  required_providers {
    lacework = {
      source  = "lacework/lacework"
      version = "~> 0.24"
    }
  }
}

provider "lacework" {
    subaccount = "shared-services-dev"
}

resource "lacework_agent_access_token" "repro_test" {
  name        = "repro-test"
  description = "test token, OK to disable after October 2022"
}
```

Applying that configuration creates a token in the `opensesame` subaccount, not `shared-services-dev`.

Now if I do a `tf state rm lacework_agent_access_token.repro_test` and re-import, it works fine -- because it's importing the agent token it created in the wrong account.

I'll change the issue title to reflect what seems to be the actual problem, but would still be happy to hear that I've just misunderstood some documentation.

**Comment by relsqui** [comment]
This appears to have been fixed at some point. 🤷🏻‍♂️

**Comment by afiune** [comment]
## YAS!
<img src="https://media1.giphy.com/media/IwAZ6dvvvaTtdI8SD5/giphy.gif"/>

This was part of the migration to API v2 - I forgot to keep you posted, apologies. 😅
