### ISSUE TITLE
Lacework Agents access token resource and data source

### ISSUE THREAD

**Issue by JPLachance** [lacework/terraform-provider-lacework#41]
Greetings,

Today, to manage Lacework agents access tokens, we must use the Lacework UI or the API.

With a Terraform resource, automating the creation and management of Lacework agents access tokens will be easier. For example, it will make it easy to create the access token and then store it in AWS Secrets Manager.

Thanks in advance for the help!

**Comment by afiune** [comment]
@JPLachance Would this resource and this data source work for you?

## Resource
```hcl
resource "lacework_agent_access_token" "k8s" {
  name        = "prod"
  description = "k8s deployment for production env"
}
```

## Data Source
```hcl
data "lacework_agent_access_token" "k8s" {
  name  = "prod"
}
```

Both expose a `token` attribute. Suggestions are accepted.

**Comment by JPLachance** [comment]
Hello!

This will work. It will allow me to create token, store it in AWS Secrets Manager, automate its rotation.

Thank you 😄
