### ISSUE TITLE
bug: Cannot add K8S activity event category to alert_rule resource controlled by Terraform

### ISSUE THREAD

**Issue by brightcohen** [lacework/terraform-provider-lacework#411]
**Describe the bug**
Using lacework provider to create Alert Rule we ran into an issue of not being able to add the value `K8SActivity` under `Event categories`. When adding it manually using the Lacework platform and running terraform we can see that the terraform provider removes the K8SActivity value.

**To Reproduce**
1. Create Alert rule using Lacework Terraform provider
2. Using Lacework console, Add the `Kubernetes Activity` under the Event categories multi selection field
3. Run terraform again, it will remove the K8SActivity value from the alert rule

```
  ~ resource "lacework_alert_rule" "alert_rule" {
      ~ event_categories        = [
            # (5 unchanged elements hidden)
            "Platform",
          - "K8sActivity",
        ]
        id                      = "TALCEFF4066E8F"
        name                    = "All Critical"
        # (9 unchanged attributes hidden)
    }
```

**Expected behavior**
All values that can be chosen in the console platform can be added via terraform

**Screenshots**

**Please complete the following information):**
 - Terraform version 1.3.2
 - Provider Version 1.0.1

**Additional context**

**Comment by afiune** [comment]
Hi @brightcohen - Thank you so much for reporting this but, we have created an internal ticket to prioritize and track the work that needs to be done to support this event category. (shouldn't be too much 😄 )

Please, keep an eye on this issue for updates, we will be working on solving this problem soon.

- https://lacework.atlassian.net/browse/ALLY-1219
