### ISSUE TITLE
bug: breaking change `limit_by_labels` in `<=1.0.1` replaced by `limit_by_label` in `1.1.0`

### ISSUE THREAD

**Issue by MaxymVlasov** [lacework/terraform-provider-lacework#421]
**Describe the bug**
1.1.0 introduced breaking change by replace [`limit_by_labels`](https://registry.terraform.io/providers/lacework/lacework/1.0.1/docs/resources/integration_ecr#limit_by_labels) existed in `<=1.0.1` by [ `limit_by_label` ](https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/integration_ecr#limit_by_label)in `1.1.0`

That brokes your modules during the update to 1.1.0, eg:

https://github.com/lacework/terraform-aws-ecr/blob/a5453530e64805c1dff9922ad1c2f6f97cf0908f/variables.tf#L37-L41

**To Reproduce**

1. Pin provider to 1.0.1
2. Create `resource lacework_integration_ecr` with [limit_by_labels](https://registry.terraform.io/providers/lacework/lacework/1.0.1/docs/resources/integration_ecr#limit_by_labels) attribute
3. Pin provider to 1.1.0  and see an error during the plan

**Expected behavior**

No breaking changes in Minor updates. That violates SemVer. Please return `limit_by_labels`

**Screenshots**
![image](https://user-images.githubusercontent.com/11096782/204808963-d039d605-c689-4242-910a-e6e462db6309.png)

**Please complete the following information):**
 - OS: Windows 10 with WSL (Ubuntu 20.04)
 - Provider Version 1.1.0

**Comment by dmurray-lacework** [comment]
Hi @MaxymVlasov you are correct, this is a breaking change. 
We did not follow semver with this bug fix. However, after consulting with the team we will not be doing a revert or a major version increase. 

We will be working on a fix for the broken modules.

**Comment by MaxymVlasov** [comment]
OK, if not SemVer, what model do you use?
Trying to understand, if `~>` version constraints are applicable for lacework providers at the same point, or not at all

`X.Y.Z` vs `~> X.Y.Z` vs `~> X.Y`

**Comment by MaxymVlasov** [comment]
Any ETA when to be realized fix for ECR?
