### ISSUE TITLE
feat: missing features Alert categories and Alert sources from alert rules

### ISSUE THREAD

**Issue by payamzowghi** [lacework/terraform-provider-lacework#515]
# Please update resource lacework_alert_rule by new feature
https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/alert_rule
https://docs.lacework.net/console/alert-categories#alert-categories
**Describe the Feature Request**
There are two new features on LW UI but terraform resource `lacework_alert_rule` doesn't support them.

- Alert categories
- Alert sources

Please add these features to the `lacework_alert_rule` resource.
https://registry.terraform.io/providers/lacework/lacework/latest/docs/resources/alert_rule

**Comment by afiune** [comment]
Hello @payamzowghi - Thank you for your feedback, we have added the `alert_categories` argument to the resource and will add `alert_sources` next.

**Comment by afiune** [comment]
We did it! https://github.com/lacework/terraform-provider-lacework/pull/551

<img src="https://media0.giphy.com/media/lMameLIF8voLu8HxWV/giphy.gif"/>

Well, it was @PengyuanZhao 😉
