### ISSUE TITLE
bug: no contstraints set, but still getting this constraint error

### ISSUE THREAD

**Issue by httpdss** [lacework/terraform-provider-lacework#564]
**Describe the bug**
im getting this error on a clean pod and on my local machine . this used to work fine

```
Partner and community providers are signed by their developers.
If you'd like to know more about provider signing, you can read about it here:
https://www.terraform.io/docs/cli/plugins/signing.html
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider lacework/lacework: no available releases match the given constraints ~> 0.2, ~> 1.15
```

**To Reproduce**
1. Run terraform init
2. See error

**Expected behavior**
provider gets downloaded correctly

**Please complete the following information):**
 - OS: Ubuntu jammy
 - Provider Version 1.15.0

**Comment by afiune** [comment]
Hello @httpdss - thank you for reaching out. 

The only thing I would imagine sets a constraint without you setting it is a module. 

Are you using a Module? Is so, which one? Could you share the plan you are running?

**Comment by FarhanSajid1** [comment]
I'm seeing the same thing, what's the workaround, we're also not setting a constraint

**Comment by afiune** [comment]
@FarhanSajid1 @httpdss Hi folks 👋🏽 - Could you help us by providing a bit more context of your current Terraform stack?
* What version of our Terraform provider are you trying to use?
* Could you share, with caution, your Terraform code?
* If not, what Terraform modules are you using?

We are here to help you with this issue, but we can't do much with the information provided.

**Comment by httpdss** [comment]
@afiune found the issue. im using fixed version on all 3 modules im using and updated the provider to latest. seems like you are setting provider versions which is fine but that brakes if you dont update all module versions
