### ISSUE TITLE
bug: alert subcategory missing

### ISSUE THREAD

**Issue by sbeaulie** [lacework/terraform-provider-lacework#570]
**Describe the bug**
Threat Intel is missing from the alert subcategories. In general this is not the first time that the terraform module lags behind the platform capabilities, would it be possible that for rules that do not specify any alert subcategories that all of them are selected by default? So that in the future is a category called SubwooferPremium is added, is also gets selected when running terraform even if you cannot yet specify it alone?

**To Reproduce**
1. create a terraform alert rule 
2. see in the UI that threat intel is not selected

**Expected behavior**
Threat Intel is selected. 

**Screenshots**

**Please complete the following information):**
 - Provider Version v0.15.0

**Additional context**
N/A

**Comment by PengyuanZhao** [comment]
@sbeaulie thanks for reporting the issue. We will look into the issue and keep you posted.
