### ISSUE TITLE
bug: remediation is not optional for policies

### ISSUE THREAD

**Issue by eambrosyupgrade** [lacework/terraform-provider-lacework#583]
**Describe the bug**
When creating a compliance policy, an empty string is interpreted as a blank and the provider receives a 400 from the Lacework API. Additionally not including the `remediation` field also 400s for the field not being blank.

Looking at [docs](https://yourlacework.lacework.net/api/v2/docs#tag/Policies/paths/~1api~1v2~1Policies/post), this is a required field in the API

**To Reproduce**

1. create a compliance policy and set `remediation` to `""` or don't include a remediation
3. Run an apply

**Expected behavior**
I should be able to provide an empty string or `null` value for Remediation based on terraform docs and `Option: True` [here](https://github.com/lacework/terraform-provider-lacework/blob/main/lacework/resource_lacework_policy_compliance.go#L58)

**Screenshots**

```
╷
│ Error: 
│   [POST] https://upgrade.lacework.net/api/v2/Policies
│   [400] Incorrect configuration of field remediation: must not be blank
│ 
│   with lacework_policy.example,
│   on test_policy.tf line 1, in resource "lacework_policy" "example":
│    1: resource "lacework_policy" "example" {
│ 

```

**Please complete the following information):**
 - OS: MacOS
 - Provider Version:
 ```
Terraform v1.5.6
on darwin_arm64
+ provider registry.terraform.io/lacework/lacework v1.15.0
```

**Additional context**

**Comment by afiune** [comment]
Thank you so much for reporting this, @eambrosyupgrade !!

<img src="https://media0.giphy.com/media/ZfK4cXKJTTay1Ava29/giphy.gif"/>
