### ISSUE TITLE
Typo in AWS CloudTrail resource docs

### ISSUE THREAD

**Issue by sftim** [lacework/terraform-provider-lacework#59]
I spotted a typographical error in https://github.com/lacework/terraform-provider-lacework/blob/7f6c89510b0279d0ff2728d76b7a8d2bfbf4abad/website/docs/r/integration_aws_ct.html.markdown

“acocunt” should be “account”

**Comment by afiune** [comment]
@sftim Thank you so much for your feedback! We will get this typo fixed right away 💯
