### ISSUE TITLE
Updating to Lacework Provider 3.1.0 causes failures with existing configs

### ISSUE THREAD

**Issue by alexeiser** [lacework/terraform-provider-lacework#90]
Updating to lacework Provider 3.1 and updating the config to wrap access_key_id && secret_access_key into a credential block

```
  credentials {
    access_key_id     = aws_iam_access_key.lacework-ecr-access_key.id
    secret_access_key = aws_iam_access_key.lacework-ecr-access_key.secret
  }
```

Causes errors during plan & apply:
Error: Unsupported ECR authentication type ''.

No additional useful information with TF_LOG=debug set

**Comment by afiune** [comment]
@alexeiser thank you again for reporting this issue you are having, unfortunately, this is an edge case where the resource you imported on previous versions of the provider did know about a change of schema on the Lacework APIs and therefore, the state of the resource is invalid or not supported.

To fix your problem you could remove the ECE resource from the terraform state and import it again.

```
$ terraform state rm 'lacework_integration_ecr.YOUR_RESOURCE_NAME'
$ terraform import 'lacework_integration_ecr.YOUR_RESOURCE_NAME' [INT_GUID]
```

To retreive the `INT_GUID` from existing integrations in your account, use the Lacework CLI command `lacework integration list`.

Apologies for the inconveniences.

**Comment by alexeiser** [comment]
I would rather migrate to the Role method - besides the creation of a new INT_GUID - are their any negatives from the lacework side? Re-Scanning of all images? for example?

**Comment by afiune** [comment]
I would agree with you, @alexeiser - Using an IAM Role is better and more secure 😉. You are probably aware of this but we just recently released a new Terraform Module that does both, the creation of an IAM Role on your AWS account and the ECR integration in your Lacework account.

Take a look and give us some feedback: https://registry.terraform.io/modules/lacework/ecr/aws/latest

![tenor-137638154](https://user-images.githubusercontent.com/5712253/111554142-5eefc180-874b-11eb-9d2d-bd0dfec03ab7.gif)

**Comment by afiune** [comment]
Closing this issue since it looks like the problem has a solution, if you have any other problem please let us know.

Thank you for your feedback! 💯
